#!/usr/bin/env python3
"""Create or update a portable autoresearch workspace from the bundled template."""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

from detect_runtime import detect_runtime


UPSTREAM_URL = "https://github.com/karpathy/autoresearch"
RESULTS_HEADER = "commit\tval_bpb\tmemory_gb\tstatus\tdescription\n"
COPYTREE_IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo", ".DS_Store")


def template_dir() -> Path:
    return Path(__file__).resolve().parent.parent / "assets" / "portable-template"


def build_pyproject(torch_profile: str) -> str:
    deps = [
        '"matplotlib>=3.10.8"',
        '"numpy>=2.2.6"',
        '"pandas>=2.3.3"',
        '"pyarrow>=21.0.0"',
        '"requests>=2.32.0"',
        '"rustbpe>=0.1.0"',
        '"tiktoken>=0.11.0"',
        '"torch==2.9.1"',
    ]
    if torch_profile == "linux-cuda":
        deps.insert(0, '"kernels>=0.11.7"')

    lines = [
        "[project]",
        'name = "autoresearch"',
        'version = "0.1.0"',
        'description = "Portable autoresearch workspace generated by autoresearch-codex"',
        'readme = "LOCAL_SETUP.md"',
        'requires-python = ">=3.10"',
        "dependencies = [",
    ]
    lines.extend(f"    {dep}," for dep in deps)
    lines.append("]")

    if torch_profile == "linux-cuda":
        lines.extend(
            [
                "",
                "[tool.uv.sources]",
                "torch = [",
                '    { index = "pytorch-cu128" },',
                "]",
                "",
                "[[tool.uv.index]]",
                'name = "pytorch-cu128"',
                'url = "https://download.pytorch.org/whl/cu128"',
                "explicit = true",
            ]
        )
    elif torch_profile == "linux-cpu":
        lines.extend(
            [
                "",
                "[tool.uv.sources]",
                "torch = [",
                '    { index = "pytorch-cpu" },',
                "]",
                "",
                "[[tool.uv.index]]",
                'name = "pytorch-cpu"',
                'url = "https://download.pytorch.org/whl/cpu"',
                "explicit = true",
            ]
        )

    lines.append("")
    return "\n".join(lines)


def current_python_minor() -> str:
    return f"{sys.version_info.major}.{sys.version_info.minor}"


def try_clone(dest: Path, repo_url: str) -> bool:
    if dest.exists():
        return False
    try:
        subprocess.run(["git", "clone", repo_url, str(dest)], check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def overlay_template(dest: Path, torch_profile: str) -> None:
    src = template_dir()
    dest.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        if item.name == "__pycache__":
            continue
        target = dest / item.name
        if item.is_dir():
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(item, target, ignore=COPYTREE_IGNORE)
        else:
            if item.suffix in {".pyc", ".pyo"}:
                continue
            shutil.copy2(item, target)
    (dest / "pyproject.toml").write_text(build_pyproject(torch_profile))
    (dest / ".python-version").write_text(current_python_minor() + "\n")
    results = dest / "results.tsv"
    if not results.exists():
        results.write_text(RESULTS_HEADER)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dest", required=True, help="Destination directory for the workspace")
    parser.add_argument("--repo-url", default=UPSTREAM_URL, help="Upstream repo to clone when the target does not exist")
    parser.add_argument("--no-clone", action="store_true", help="Create the destination locally instead of cloning upstream")
    args = parser.parse_args()

    dest = Path(args.dest).expanduser().resolve()
    runtime = detect_runtime()

    cloned = False
    if not args.no_clone:
        cloned = try_clone(dest, args.repo_url)
    if not dest.exists():
        dest.mkdir(parents=True, exist_ok=True)

    overlay_template(dest, runtime["torch_profile"])

    print(f"Workspace ready at: {dest}")
    print(f"Runtime profile: {runtime['summary']}")
    print(f"Cloned upstream: {'yes' if cloned else 'no'}")
    print("Next steps:")
    print(f"  cd {dest}")
    print("  uv sync")
    print("  uv run prepare.py --num-shards 2")
    print("  uv run train.py > run.log 2>&1")


if __name__ == "__main__":
    main()
